Collection view database: created the database for categories
AndreeaSburlea/ShopApp pull request #10
Opened 2022-06-16 07:14 UTC by AndreeaSburlea

## Changes in code

- added a database for the categories collection view

## Screenshot
<img width="374" alt="Screenshot 2022-06-16 at 09 42 08" src="https://user-images.githubusercontent.com/103115884/174013455-0b0c0c3b-a278-4fbe-ad2c-6632d0cd8385.png">

2022-06-17 09:49 UTC, VivianaSara commented on ShopApp/ShopApp/Controller/HomeViewController.swift
> +                    let data = try await image.data(maxSize: 1 * 100 * 100)
do block should be aligned to the rest of code

2022-06-17 09:49 UTC, VivianaSara commented on ShopApp/ShopApp/Controller/HomeViewController.swift
> +                    category.setImage(image: imageData)
there should be an empty space

2022-06-17 09:49 UTC, VivianaSara commented on ShopApp/ShopApp/Controller/HomeViewController.swift
> +
delete empty space

2022-06-17 09:49 UTC, VivianaSara commented on ShopApp/ShopApp/Controller/HomeViewController.swift
> +            categoryList.append(category)
empty space needed

2022-06-17 10:07 UTC, VivianaSara approved these changes

2022-06-22 07:41 UTC, ralumarusca requested changes

2022-06-22 07:41 UTC, ralumarusca commented on ShopApp/ShopApp/Controller/HomeViewController.swift
> +                    let path = category.value as! String
instead of force unwrapping you could cast the snapshot.value to [String: String] instead of NSDictionary

2022-06-22 07:41 UTC, ralumarusca commented on ShopApp/ShopApp/Controller/HomeViewController.swift
> +        completion(imageData)
this block is not aligned correctly

2022-06-22 08:08 UTC, ralumarusca approved these changes

2022-06-22 08:16 UTC, merged