Replace async blocks
AndreeaSburlea/ShopApp pull request #12
Opened 2022-06-21 13:36 UTC by VivianaSara

## New features

- complition handler

## Changes in code

- replace async blocks with completion handler 

## Screenshot

- Same as before

2022-06-22 09:19 UTC, ralumarusca requested changes

2022-06-22 09:19 UTC, ralumarusca commented on ShopApp/ShopApp/Controller/ProductDetailsViewController.swift
> +     func favoritesFunction(complition: @escaping (String) -> Void) {
Rename the function to a more intuitive name, like favoritesAction or favoritesToggle. Also there is a typo, "completion"

2022-06-22 09:19 UTC, ralumarusca commented on ShopApp/ShopApp/Controller/ProductDetailsViewController.swift
> +                 complition("added")
why do you need the completion block?

2022-06-22 09:19 UTC, ralumarusca commented on ShopApp/ShopApp/Controller/ProductDetailsViewController.swift
> +     }
This method is pretty similar to **favoritesFunction**, maybe you can creat just one

2022-06-23 09:14 UTC, AndreeaSburlea commented on ShopApp/ShopApp/Controller/ProductDetailsViewController.swift
>          let ref = Database.database().reference()
You can create 'ref' as a global constant since it is used in line 105, 107, 114, 132 and 160

2022-06-23 11:10 UTC, ralumarusca requested changes

2022-06-23 11:10 UTC, ralumarusca commented on ShopApp/ShopApp/Controller/ProductDetailsViewController.swift
> +        if isFavorite == false {
Here instead of comparing the value with a bool you can just write: **if !isFavorite**

2022-06-23 11:10 UTC, ralumarusca commented on ShopApp/ShopApp/Controller/ProductDetailsViewController.swift
> +    func addToCartAction(size: String, complition: @escaping (String) -> Void) {
typo: **completion**

2022-06-23 11:10 UTC, ralumarusca commented on ShopApp/ShopApp/Controller/ProductDetailsViewController.swift
> +    func getComments(complition: @escaping () -> Void) {
typo: **completion**

2022-06-23 11:10 UTC, ralumarusca commented on ShopApp/ShopApp/Controller/ProductTableViewController.swift
> +    func getImages(root: String, complition: @escaping (UIImage) -> Void) {
typo: **completion**

2022-06-23 12:54 UTC, ralumarusca approved these changes

2022-06-23 12:55 UTC, AndreeaSburlea approved these changes

2022-06-24 05:26 UTC, merged