Create products table by a specific category
AndreeaSburlea/ShopApp pull request #6
Opened 2022-06-03 10:01 UTC by VivianaSara

## New features

- table view controller for show every product with the same selected category from Home Page

## Changes in code

- add a new table view controller when a collection cell ( from Home Page ) is selected
- add a back button to go back to Home Page

## Screenshot

<img width="347" alt="Screenshot 2022-06-03 at 13 00 17" src="https://user-images.githubusercontent.com/103035689/171833342-8fb7c875-5db2-4175-bb12-7885a6914127.png">

2022-06-07 07:50 UTC, madalinaCojocaru1 requested changes

2022-06-07 07:50 UTC, madalinaCojocaru1 commented on ShopApp/ShopApp/Controller/ProductTableViewController.swift
> +    func dataRead() async {
let`s remane this to getAllProducts

2022-06-07 07:50 UTC, madalinaCojocaru1 commented on ShopApp/ShopApp/Controller/ProductTableViewController.swift
> +    func getImagesFromRoot(root: String) async -> [UIImage] {
also we can rename this getAllImages

2022-06-07 07:50 UTC, madalinaCojocaru1 commented on ShopApp/ShopApp/Controller/HomeViewController.swift
> +
we can remove this empty line

2022-06-07 12:21 UTC, madalinaCojocaru1 approved these changes

2022-06-09 10:30 UTC, paulpop10 approved these changes

2022-06-09 10:59 UTC, merged